version: '3.1'
services:
  db:
    image: mariadb:10.6
    container_name: wordpress_mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=owncloud
      - MYSQL_DATABASE=wordpressdb
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    command: ["--max-allowed-packet=128M", "--innodb-log-file-size=64M"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-u", "root", "--password=wordpress"]
      interval: 10s
      timeout: 5s
      retries: 5

        #MYSQL_RANDOM_ROOT_PASSWORD: '1'
    #volumes:
     # - db:/var/lib/mysql
