#!/bin/bash

sudo yum install -y yum-utils device-mapper-persistent-data lvm2

sudo yum-config-manager  --add-repo https://download.docker.com/linux/centos/docker-ce.repo

sudo yum install docker -y

sudo systemctl enable docker

sudo systemctl start docker

sudo systemctl status docker

sudo docker pull mcr.microsoft.com/mssql/server

sudo docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=MiEmMeSa*" -p 1433:1433 --name sqlpreview --hostname sqlpreview -d mcr.microsoft.com/mssql/server:latest

/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'MiEmMeSa*'